### ISSUE TITLE
[DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin

### ISSUE THREAD

**Issue by Judahh** [cansin/next-with-workbox#13]
[DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
Warning appears when using Webpack5

**Comment by cansin** [comment]
@Judahh should be fixed since `>=3.0.0`

Commit: https://github.com/cansin/next-with-workbox/commit/aad0b252f70864a844761b8eb4bd19c809fabc6e 
Version: https://www.npmjs.com/package/next-with-workbox/v/3.0.0
