### ISSUE TITLE
sw.js got 404 status for middleware.js

### ISSUE THREAD

**Issue by tetuaoro** [cansin/next-with-workbox#20]
Test on

-  **Brave** : Version 1.41.96 Chromium: 103.0.5060.114 (Build officiel) (64 bits)

-  **Firefox** : 102.0.1 (64 bits)

-  **Chrome** : 103.0.5060.134

Hi all,

I got this error on console. I just followed steps in your README.

![image](https://user-images.githubusercontent.com/65575727/180579631-ccc8e572-b71f-4167-a99c-0d8db35a95d2.png)

I tried both InjectManifest and GenerateSW method already to remove the url which includes `middleware` :

```javascript
import { cacheNames } from "workbox-core"
import { registerRoute } from "workbox-routing"
import { CacheFirst, NetworkFirst } from "workbox-strategies"
import { CacheableResponsePlugin } from "workbox-cacheable-response"
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching"
import { ExpirationPlugin } from "workbox-expiration"
import { offlineFallback } from "workbox-recipes"

cleanupOutdatedCaches()

// eslint-disable-next-line no-restricted-globals,no-underscore-dangle
precacheAndRoute(self.__WB_MANIFEST)

const cacheableOk = new CacheableResponsePlugin({
  statuses: [0, 200],
})

const expiration = new ExpirationPlugin({
  maxEntries: 50,
  maxAgeSeconds: 60 * 60 * 24 * 7 /* 1 week */,
  purgeOnQuotaError: true,
})

/**
 *
 * @param {Object} params
 * @param {URL} params.url
 */
const matchPreCache = ({ url }) => {
  const middleware = url.pathname.includes("middleware-build-manifest")
  const publicFiles = url.pathname.startsWith("/fonts") || url.pathname.startsWith("/icons") || url.pathname.startsWith("/images")
  const nextFiles = url.pathname.includes("media") || url.pathname.includes("static")

  return !middleware && (publicFiles || nextFiles)
}

registerRoute(
  matchPreCache,
  new CacheFirst({
    cacheName: cacheNames.precache,
    plugins: [expiration, cacheableOk],
  }),
  "GET"
)

/**
 *
 * @param {Object} params
 * @param {URL} params.url
 */
const matchRuntime = () => {
  return !matchPreCache()
}

registerRoute(
  matchRuntime,
  new NetworkFirst({
    cacheName: cacheNames.runtime,
    plugins: [cacheableOk],
  })
)

offlineFallback()
```

Here the development link to show the error [maneatahitiservices](https://dev.maneatahitiservices.pf/). This link use `GenerateSW` method.

Hope you can help,

**Comment by tetuaoro** [comment]
fixed tanks a lot

**Comment by alexandrenicol** [comment]
Hello,

I had a similar issue where the base config added `middleware-build-manifest.js` and `middleware-react-loadable-manifest.js` to the service worker, which would then 404 and cause the service worked to fail to install.

I had to add the following exclusions to the configuration to make it work:

```
workbox: {
    swSrc: "worker.js",
    exclude: [
      /middleware-build-manifest\.js/i,
      /middleware-react-loadable-manifest\.js/i,
    ]
  }
```

I don't know whether it could be related to some of the work the Next.js team have been doing in Next 12.2, which I think included a few changes to the way middlewares works in Next.js?

cc @cansin
